import express from 'express';
import Note from '../models/Note.js';
import { protect } from '../middleware/auth.js';

const router = express.Router();

router.get('/', protect, async (req, res) => {
  try {
    const { relatedContact, relatedDeal, isPinned } = req.query;
    const filter = { user: req.user._id };

    if (relatedContact) filter.relatedContact = relatedContact;
    if (relatedDeal) filter.relatedDeal = relatedDeal;
    if (isPinned) filter.isPinned = isPinned === 'true';

    const notes = await Note.find(filter)
      .populate('createdBy', 'name email')
      .populate('relatedContact', 'name email')
      .populate('relatedDeal', 'title value')
      .sort({ isPinned: -1, createdAt: -1 });

    res.json(notes);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

router.get('/:id', protect, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user: req.user._id })
      .populate('createdBy')
      .populate('relatedContact')
      .populate('relatedDeal');

    if (!note) {
      return res.status(404).json({ error: 'Note not found' });
    }

    res.json(note);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

router.post('/', protect, async (req, res) => {
  try {
    const note = new Note({
      ...req.body,
      user: req.user._id,
      createdBy: req.user._id
    });

    await note.save();
    res.status(201).json(note);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

router.patch('/:id', protect, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user: req.user._id });
    if (!note) {
      return res.status(404).json({ error: 'Note not found' });
    }

    if (note.autoGenerated && Object.keys(req.body).some(k => k !== 'isPinned' && k !== 'tags')) {
      return res.status(403).json({ error: 'Cannot edit auto-generated notes' });
    }

    Object.assign(note, req.body);
    await note.save();

    res.json(note);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

router.delete('/:id', protect, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user: req.user._id });

    if (!note) {
      return res.status(404).json({ error: 'Note not found' });
    }

    if (note.autoGenerated && note.source === 'voice_agent') {
      return res.status(403).json({ error: 'Cannot delete auto-generated voice agent notes' });
    }

    await note.deleteOne();
    res.json({ message: 'Note deleted successfully' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

router.patch('/:id/pin', protect, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user: req.user._id });
    if (!note) {
      return res.status(404).json({ error: 'Note not found' });
    }

    note.isPinned = !note.isPinned;
    await note.save();

    res.json(note);
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

export default router;
