import mongoose from 'mongoose';

const noteSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  content: {
    type: String,
    required: true,
    trim: true
  },
  relatedContact: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Lead',
    index: true
  },
  relatedDeal: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Deal',
    index: true
  },
  relatedTask: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Task'
  },
  relatedCall: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CallLog'
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  source: {
    type: String,
    enum: ['manual', 'voice_agent', 'email', 'call', 'system'],
    default: 'manual'
  },
  voiceAgentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'VoiceAgent'
  },
  isPinned: {
    type: Boolean,
    default: false
  },
  tags: [String],
  attachments: [{
    fileName: String,
    fileUrl: String,
    fileType: String,
    fileSize: Number
  }],
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

noteSchema.index({ user: 1, createdAt: -1 });
noteSchema.index({ relatedContact: 1, createdAt: -1 });
noteSchema.index({ relatedDeal: 1, createdAt: -1 });

noteSchema.pre('validate', function(next) {
  if (!this.relatedContact && !this.relatedDeal && !this.relatedTask && !this.relatedCall) {
    next(new Error('Note must be related to at least one entity (contact, deal, task, or call)'));
  } else {
    next();
  }
});

export default mongoose.model('Note', noteSchema);
